backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/_uploads" # Folder where user uploaded files should go
public_folder: "/uploads" # Folder accessible from the public

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
